version: '3'
services:
  app:
    build:
      context: .
    privileged: true
    ports:
      - "5007:5007"
    restart: unless-stopped
    command: bash -c "
      alembic revision --autogenerate &&
      alembic upgrade head &&
      uvicorn app.main:app --reload --port 5007 --host 0.0.0.0
      "
    volumes:
      - ./migrations/versions:/migrations/versions
      - ./database:/database
